server:
  port: 8085

spring:
  application:
    name: backend-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/productsdb
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

opensearch:
  uris: localhost:9200
  username: admin
  password: admin
  wilsonScoreField: wilson-score